version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - pip install aws-sam-cli
      
  pre_build:
    commands:
      - npm ci

      - cd src/handlers
      - npm ci
      - cd ../..

      # Create FFmpeg layer
      - mkdir -p ffmpeg-layer/nodejs/bin
      - cd ffmpeg-layer
      - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
      - tar xf ffmpeg-release-amd64-static.tar.xz
      - cp ffmpeg-*-amd64-static/ffmpeg nodejs/bin/
      - chmod 755 nodejs/bin/ffmpeg

      # Create package.json for the layer
      - |
        echo '{
          "name": "ffmpeg-layer",
          "version": "1.0.0",
          "description": "FFmpeg binaries for Lambda",
          "main": "index.js"
        }' > nodejs/package.json

      # Create layer.zip
      - zip -r ffmpeg-layer.zip nodejs/

      # Upload layer to S3
      - aws s3 cp ffmpeg-layer.zip s3://${ARTIFACT_BUCKET}/ffmpeg-layer.zip
      - cd ..
      
  build:
    commands:
      - npm run build
      - sam build -t cloudformation/resources.yaml
      
  post_build:
    commands:
      - sam package
          --s3-bucket ${ARTIFACT_BUCKET} 
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - appspec.yml
    - cloudformation/*
    - dist/**/*
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - 'src/handlers/node_modules/**/*'