AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Resources Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qa]
  BucketPrefix:
    Type: String
    Default: voice-recorder
  ArtifactBucket:
    Type: String
    Description: Pipeline artifact bucket name

Resources:
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketPrefix}-${Environment}-${AWS::AccountId} 
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']  # Replace with your frontend domain in production
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteTempFiles
            Prefix: temp/
            Status: Enabled
            ExpirationInDays: 1

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt AudioBucket.Arn
                  - !Sub ${AudioBucket.Arn}/*

  VoiceRecorderApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub voice-recorder-api-${Environment}
      Description: Voice Recorder API
      EndpointConfiguration:
        Types: [REGIONAL]

  AudioResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ParentId: !GetAtt VoiceRecorderApi.RootResourceId
      PathPart: audio

  AddResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ParentId: !Ref AudioResource
      PathPart: add

  AddMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ResourceId: !Ref AddResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddAudioFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  MergeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ParentId: !Ref AudioResource
      PathPart: merge

  MergeMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ResourceId: !Ref MergeResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MergeAudioFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  RetrieveResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ParentId: !Ref AudioResource
      PathPart: retrieve

  RetrieveMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ResourceId: !Ref RetrieveResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAudioFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  RemoveResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ParentId: !Ref AudioResource
      PathPart: remove

  RemoveMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VoiceRecorderApi
      ResourceId: !Ref RemoveResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteAudioFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AddMethod
      - MergeMethod
      - RetrieveMethod
      - RemoveMethod
    Properties:
      RestApiId: !Ref VoiceRecorderApi

  GatewayResponseDefault4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT,DELETE'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref VoiceRecorderApi

  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT,DELETE'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref VoiceRecorderApi

  AddAudioPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AddAudioFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceRecorderApi}/*/*/*

  MergeAudioPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MergeAudioFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceRecorderApi}/*/*/*

  GetAudioPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetAudioFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceRecorderApi}/*/*/*

  DeleteAudioPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteAudioFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VoiceRecorderApi}/*/*/*

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref VoiceRecorderApi
      StageName: !Ref Environment

  FFmpegLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub ffmpeg-layer-${Environment}
      Description: FFmpeg binaries for audio processing
      Content:
        S3Bucket: !Ref ArtifactBucket
        S3Key: ffmpeg-layer.zip
      CompatibleRuntimes:
        - nodejs18.x
      CompatibleArchitectures:
        - x86_64

  AddAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/handlers
      Handler: addAudio.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref AudioBucket
          ENVIRONMENT: !Ref Environment

  MergeAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/handlers
      Handler: mergeAudio.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 180
      Layers:
        - !Ref FFmpegLayer
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref AudioBucket
          ENVIRONMENT: !Ref Environment

  GetAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/handlers
      Handler: getAudio.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref AudioBucket
          ENVIRONMENT: !Ref Environment

  DeleteAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/handlers
      Handler: deleteAudio.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref AudioBucket
          ENVIRONMENT: !Ref Environment

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${VoiceRecorderApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref AudioBucket